spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arnabbanerjee2017/SpringConfigServerConfiguration.git
  application:
    name: spring-config-server
server:
  port: 8888
